[target.thumbv6m-none-eabi]
rustflags = [
  "-C", "link-arg=-Tlink.x",
]

[target.thumbv7em-none-eabihf]
rustflags = [
  "-C", "link-arg=-Tlink.x",
]

[target.thumbv8m.main-none-eabihf]
rustflags = [
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x",
]
